import React from "react";
import type { NextPage } from 'next'
import Head from "next/head";
import { Layout } from 'antd';

const { Content } = Layout;

const defaultLayout = (props: { children: React.ReactNode }) => {
  return (
    <Layout>
        <Head>
            <title>CEAWEBSYSTEMS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
      <Content>
        <div className="container">{props.children}</div>
      </Content>
    </Layout>
  );
}

export default defaultLayout;